# pipeline name
name: Ci Pipeline  

# tells that the pipeline jobs should run only on main branch which is prod. ready
on:
  push:
    branches: [ main ]

# jobs: steps which need to be performed after push event(trigger)
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  


# indentation is very important in yaml files, double space after every param